FROM node:23-alpine3.20

WORKDIR /app 

COPY package*.json . 

COPY . . 

RUN npm install 

RUN npm run build 

FROM nginx:1.27.3-alpine 

COPY --from=build /app/build /usr/share/nginx/html

EXPOSE 80 

CMD [ "nginx", "-g", "daemon off;" ]